export enum SwaggerTemplateType {
  INDEX_OBJECT = 'index-object',
  INDEX_ARRAY = 'index-array',
  METHOD = 'method',
  METHODS = 'methods',
  METHOD_PARAMETER = 'method-parameter',
  PARAMETER = 'parameter',
  PARAMETERS = 'parameters',
  PARAMETER_OBJECT = 'parameter-object',
  PROPERTY = 'property',
  REQUEST_BODY = 'request-body',
  RESPONSE_ARRAY = 'response-array',
  RESPONSE = 'response',
  ROUTE_METHOD = 'route-method',
  SCHEMA = 'schema',
  SCHEMAS = 'schemas',
  TAG = 'tag',
  TAGS = 'tags',
  SPEC = 'spec',
}
